basePath: /
definitions:
  helper.HTTPResponse:
    properties:
      data: {}
      error_msg:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
  models.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: lumoshive.academy@gmail.com
    name: API Support
    url: https://academy.lumoshive.com/contact-us
  description: This is API for system voucher.
  license:
    name: Lumoshive Academy
    url: https://academy.lumoshive.com
  termsOfService: http://example.com/terms/
  title: Sistem Voucher
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login first for all access.
      parameters:
      - description: Login payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Login'
      produces:
      - application/json
      responses:
        "200":
          description: successfully login
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: Login feature
      tags:
      - login
  /vouchers:
    get:
      consumes:
      - application/json
      description: List Get Voucher By Query Param.
      produces:
      - application/json
      responses:
        "200":
          description: successfully retrieved Voucher
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "404":
          description: Voucher not found
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Get Voucher By Query Param
      tags:
      - Get Voucher By Query Param
    post:
      consumes:
      - application/json
      description: Feature Use Voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Use Voucher
      tags:
      - Use Voucher
  /vouchers/:id:
    delete:
      consumes:
      - application/json
      description: Feature to delete a voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response with voucher data
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Soft Deletes
      tags:
      - Soft Deletes
    put:
      consumes:
      - application/json
      description: Feature to update a voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response with voucher data
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Update Voucher
      tags:
      - Update Voucher
  /vouchers/:user_id:
    get:
      consumes:
      - application/json
      description: Feature Find Voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Find Voucher
      tags:
      - Find Voucher
  /vouchers/:user_id/validate:
    get:
      consumes:
      - application/json
      description: Feature Validate Voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Validate Voucher
      tags:
      - Validate Voucher
  /vouchers/create:
    post:
      consumes:
      - application/json
      description: Feature to create a voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response with voucher data
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Create Voucher
      tags:
      - Create Voucher
  /vouchers/redeem:
    post:
      consumes:
      - application/json
      description: Feature to create a voucher
      produces:
      - application/json
      responses:
        "200":
          description: Success response with voucher data
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Create Voucher
      tags:
      - Create Voucher
  /vouchers/redeem-history/:user_id:
    get:
      consumes:
      - application/json
      description: Feature Get Redeem History
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Get Redeem History
      tags:
      - Get Redeem History
  /vouchers/redeem-points:
    get:
      consumes:
      - application/json
      description: List Show Redeem Points.
      produces:
      - application/json
      responses:
        "200":
          description: successfully retrieved Voucher
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "404":
          description: Voucher not found
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Show Redeem Points
      tags:
      - Show Redeem Points
  /vouchers/usage-history/:user_id:
    get:
      consumes:
      - application/json
      description: Feature Get Usage Users History
      produces:
      - application/json
      responses:
        "200":
          description: Success response with voucher data
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Get Usage Users History
      tags:
      - Get Usage Users History
  /vouchers/users-by-voucher/:voucher_code:
    get:
      consumes:
      - application/json
      description: Feature Get User By Voucher Code
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Get User By Voucher Code
      tags:
      - Get User By Voucher Code
schemes:
- http
securityDefinitions:
  id_key:
    in: header
    name: id_key
    type: apiKey
  token:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
