basePath: /
definitions:
  helper.HTTPResponse:
    properties:
      data: {}
      error_msg:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
  models.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: lumoshive.academy@gmail.com
    name: API Support
    url: https://academy.lumoshive.com/contact-us
  description: This is API for system voucher.
  license:
    name: Lumoshive Academy
    url: https://academy.lumoshive.com
  termsOfService: http://example.com/terms/
  title: Sistem Voucher
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login first for all access.
      parameters:
      - description: Login payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Login'
      produces:
      - application/json
      responses:
        "200":
          description: successfully login
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      summary: Login feature
      tags:
      - login
  /vouchers/reedem-points:
    get:
      consumes:
      - application/json
      description: List Redeem Points.
      produces:
      - application/json
      responses:
        "200":
          description: successfully retrieved Redeem Points
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "404":
          description: Redeem Points not found
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.HTTPResponse'
      security:
      - token: []
      - id_key: []
      summary: Redeem Points
      tags:
      - Redeem Points
schemes:
- http
securityDefinitions:
  id_key:
    in: header
    name: id_key
    type: apiKey
  token:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
